name: CI/CD Podman Python App with GHCR

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: self-hosted
    outputs:
      sha: ${{ steps.set-sha.outputs.sha }}
      exists: ${{ steps.check_image.outputs.exists }}
    steps:
      - uses: actions/checkout@v3

      - name: Set image SHA
        id: set-sha
        run: echo "sha=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Check and Build
        id: check_image
        run: |
          # Переводим логин в нижний регистр для Docker
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_BASE="ghcr.io/${OWNER_LC}/python-app"
          IMAGE_RUNTIME="${IMAGE_BASE}:runtime-${{ github.sha }}"
          IMAGE_TEST="${IMAGE_BASE}:test-${{ github.sha }}"

          if docker manifest inspect $IMAGE_RUNTIME > /dev/null 2>&1; then
            echo "Image exists. Skipping build."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT

            # Сборка и пуш теста
            docker build --target test -t $IMAGE_TEST .
            docker push $IMAGE_TEST

            # Сборка и пуш рантайма
            docker build --target runtime -t $IMAGE_RUNTIME .
            docker push $IMAGE_RUNTIME
          fi
        shell: bash

  test:
    runs-on: self-hosted
    needs: build-and-push
    # Запускаем только если билд прошел (или был скипнут, но имидж есть)
    steps:
      - name: Runs tests via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            set -e
            OWNER_LC=$(echo "${{ github.repository_owner
